from pathlib import Path
base = Path('/mnt/data/customer-review-app')
files = {}

def add(path, content):
    files[path] = content.lstrip('\n')

add('README.md', r'''
# Customer Review App (Microservices + MVC)

A complete **Customer Review App** built with **Node.js, Express, MongoDB, Docker, and JWT authentication** using a **microservices architecture** with **MVC** inside each service.

This project is aligned to the IS312 capstone idea of a system where users can:
- register and log in
- browse products/services
- write reviews only when authenticated
- view their profile
- update and delete only their own reviews

## Architecture

Services:
- **api-gateway** - single entry point for browser and API traffic
- **auth-service** - register, login, token validation
- **product-service** - manage and list products/services
- **review-service** - create, update, delete, and list reviews
- **user-service** - user profile and user review summary
- **frontend** - static Bootstrap web UI

Each backend service uses MVC:
- `models/`
- `controllers/`
- `routes/`
- `middlewares/`
- `config/`

## Tech Stack
- Node.js
- Express.js
- MongoDB + Mongoose
- JWT
- Docker Compose
- Bootstrap 5
- Vanilla JavaScript frontend

## Main Features
- User registration and login
- Protected review posting
- Product browsing
- Review listing by product
- Profile page with user information and authored reviews
- Users can update/delete only their own reviews
- Seed data for demo products/services

## Folder Structure

```text
customer-review-app/
├── api-gateway/
├── auth-service/
├── product-service/
├── review-service/
├── user-service/
├── frontend/
├── docker-compose.yml
└── README.md
```

## How to Run

### 1. Start everything
```bash
docker compose up --build
```

### 2. Open the app
```text
http://localhost:8080
```

## Default Ports
- Gateway: `8080`
- Auth Service: `4001`
- Product Service: `4002`
- Review Service: `4003`
- User Service: `4004`
- Frontend: served through gateway
- MongoDB: `27017`

## Seeded Demo Products
The product service seeds a few products automatically when it starts.

## API Summary

### Auth
- `POST /api/auth/register`
- `POST /api/auth/login`
- `GET /api/auth/verify`

### Products
- `GET /api/products`
- `GET /api/products/:id`
- `POST /api/products/seed`

### Reviews
- `GET /api/reviews/product/:productId`
- `POST /api/reviews`
- `PUT /api/reviews/:id`
- `DELETE /api/reviews/:id`
- `GET /api/reviews/user/:userId`

### Users
- `GET /api/users/me`
- `GET /api/users/:userId/reviews`

## Notes
- Every service uses its own MongoDB database for better microservice separation.
- The API gateway forwards requests to the appropriate internal service.
- JWT is generated by the auth service and validated by downstream services using the shared secret.

## Quick Test Flow
1. Open the app.
2. Register a new user.
3. Log in.
4. Browse products.
5. Open a product.
6. Post a review.
7. Edit or delete your own review.
8. Open profile page to see your details and reviews.
''')

common_package = r'''
{
  "name": "SERVICE_NAME",
  "version": "1.0.0",
  "main": "src/server.js",
  "scripts": {
    "start": "node src/server.js",
    "dev": "nodemon src/server.js"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "mongoose": "^8.5.1",
    "morgan": "^1.10.0",
    "axios": "^1.7.2",
    "jsonwebtoken": "^9.0.2",
    "bcryptjs": "^2.4.3"
  },
  "devDependencies": {
    "nodemon": "^3.1.4"
  }
}
'''

common_server = r'''
const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const connectDB = require('./config/db');
require('dotenv').config();

const app = express();
connectDB();

app.use(cors());
app.use(express.json());
app.use(morgan('dev'));

app.get('/health', (req, res) => {
  res.json({ service: process.env.SERVICE_NAME, status: 'ok' });
});

ROUTES_PLACEHOLDER

const PORT = process.env.PORT || 4000;
app.listen(PORT, () => {
  console.log(`${process.env.SERVICE_NAME} running on port ${PORT}`);
});
'''

common_db = r'''
const mongoose = require('mongoose');

module.exports = async function connectDB() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log(`Mongo connected for ${process.env.SERVICE_NAME}`);
  } catch (error) {
    console.error('Mongo connection error:', error.message);
    process.exit(1);
  }
};
'''

# auth-service
add('auth-service/package.json', common_package.replace('SERVICE_NAME', 'auth-service'))
add('auth-service/.env.example', r'''
PORT=4001
SERVICE_NAME=auth-service
MONGO_URI=mongodb://mongo:27017/authdb
JWT_SECRET=supersecretjwtkey
''')
add('auth-service/Dockerfile', r'''
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4001
CMD ["npm", "start"]
''')
add('auth-service/src/server.js', common_server.replace('ROUTES_PLACEHOLDER', "app.use('/api/auth', require('./routes/authRoutes'));"))
add('auth-service/src/config/db.js', common_db)
add('auth-service/src/models/User.js', r'''
const mongoose = require('mongoose');

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    gender: { type: String, default: 'Not specified' },
    address: { type: String, default: '' },
    contactNumber: { type: String, default: '' },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true }
  },
  { timestamps: true }
);

module.exports = mongoose.model('User', userSchema);
''')
add('auth-service/src/controllers/authController.js', r'''
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const User = require('../models/User');

function generateToken(user) {
  return jwt.sign(
    { id: user._id, email: user.email, name: user.name },
    process.env.JWT_SECRET,
    { expiresIn: '7d' }
  );
}

exports.register = async (req, res) => {
  try {
    const { name, gender, address, contactNumber, email, password } = req.body;

    const existingUser = await User.findOne({ email });
    if (existingUser) {
      return res.status(400).json({ message: 'User already exists with this email.' });
    }

    const hashedPassword = await bcrypt.hash(password, 10);
    const user = await User.create({
      name,
      gender,
      address,
      contactNumber,
      email,
      password: hashedPassword
    });

    const token = generateToken(user);

    res.status(201).json({
      message: 'Registration successful.',
      token,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        gender: user.gender,
        address: user.address,
        contactNumber: user.contactNumber
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.login = async (req, res) => {
  try {
    const { email, password } = req.body;

    const user = await User.findOne({ email });
    if (!user) {
      return res.status(401).json({ message: 'Invalid email or password.' });
    }

    const isMatch = await bcrypt.compare(password, user.password);
    if (!isMatch) {
      return res.status(401).json({ message: 'Invalid email or password.' });
    }

    const token = generateToken(user);

    res.json({
      message: 'Login successful.',
      token,
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        gender: user.gender,
        address: user.address,
        contactNumber: user.contactNumber
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.verify = async (req, res) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ message: 'No token provided.' });
    }

    const token = authHeader.split(' ')[1];
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    const user = await User.findById(decoded.id).select('-password');

    if (!user) {
      return res.status(404).json({ message: 'User not found.' });
    }

    res.json({ user });
  } catch (error) {
    res.status(401).json({ message: 'Invalid token.' });
  }
};
''')
add('auth-service/src/routes/authRoutes.js', r'''
const express = require('express');
const router = express.Router();
const authController = require('../controllers/authController');

router.post('/register', authController.register);
router.post('/login', authController.login);
router.get('/verify', authController.verify);

module.exports = router;
''')

# product-service
add('product-service/package.json', common_package.replace('SERVICE_NAME', 'product-service'))
add('product-service/.env.example', r'''
PORT=4002
SERVICE_NAME=product-service
MONGO_URI=mongodb://mongo:27017/productdb
JWT_SECRET=supersecretjwtkey
''')
add('product-service/Dockerfile', r'''
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4002
CMD ["npm", "start"]
''')
add('product-service/src/server.js', common_server.replace('ROUTES_PLACEHOLDER', "app.use('/api/products', require('./routes/productRoutes'));"))
add('product-service/src/config/db.js', common_db)
add('product-service/src/models/Product.js', r'''
const mongoose = require('mongoose');

const productSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    category: { type: String, required: true },
    description: { type: String, required: true },
    imageUrl: { type: String, default: '' },
    price: { type: Number, default: 0 },
    averageRating: { type: Number, default: 0 }
  },
  { timestamps: true }
);

module.exports = mongoose.model('Product', productSchema);
''')
add('product-service/src/controllers/productController.js', r'''
const Product = require('../models/Product');

exports.seedProducts = async (req, res) => {
  try {
    const count = await Product.countDocuments();
    if (count > 0) {
      return res.json({ message: 'Products already seeded.' });
    }

    const products = [
      {
        name: 'Smart Fitness Watch',
        category: 'Electronics',
        description: 'A smart watch with fitness tracking, heart-rate monitoring, and long battery life.',
        imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80',
        price: 199.99
      },
      {
        name: 'Premium Coffee Grinder',
        category: 'Home Appliance',
        description: 'A compact grinder for fresh coffee beans with multiple grind settings.',
        imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        price: 89.99
      },
      {
        name: 'Online Graphic Design Course',
        category: 'Service',
        description: 'A practical design course that teaches branding, layouts, and digital creativity.',
        imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
        price: 49.99
      }
    ];

    await Product.insertMany(products);
    res.status(201).json({ message: 'Products seeded successfully.' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.getProducts = async (req, res) => {
  try {
    const products = await Product.find().sort({ createdAt: -1 });
    res.json(products);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.getProductById = async (req, res) => {
  try {
    const product = await Product.findById(req.params.id);
    if (!product) {
      return res.status(404).json({ message: 'Product not found.' });
    }
    res.json(product);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
''')
add('product-service/src/routes/productRoutes.js', r'''
const express = require('express');
const router = express.Router();
const productController = require('../controllers/productController');

router.get('/', productController.getProducts);
router.get('/:id', productController.getProductById);
router.post('/seed', productController.seedProducts);

module.exports = router;
''')

# review-service
add('review-service/package.json', common_package.replace('SERVICE_NAME', 'review-service'))
add('review-service/.env.example', r'''
PORT=4003
SERVICE_NAME=review-service
MONGO_URI=mongodb://mongo:27017/reviewdb
JWT_SECRET=supersecretjwtkey
PRODUCT_SERVICE_URL=http://product-service:4002
''')
add('review-service/Dockerfile', r'''
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4003
CMD ["npm", "start"]
''')
add('review-service/src/server.js', common_server.replace('ROUTES_PLACEHOLDER', "app.use('/api/reviews', require('./routes/reviewRoutes'));"))
add('review-service/src/config/db.js', common_db)
add('review-service/src/models/Review.js', r'''
const mongoose = require('mongoose');

const reviewSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true },
    userName: { type: String, required: true },
    productId: { type: String, required: true },
    rating: { type: Number, required: true, min: 1, max: 5 },
    title: { type: String, required: true },
    comment: { type: String, required: true }
  },
  { timestamps: true }
);

module.exports = mongoose.model('Review', reviewSchema);
''')
add('review-service/src/middlewares/authMiddleware.js', r'''
const jwt = require('jsonwebtoken');

module.exports = function authMiddleware(req, res, next) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ message: 'Unauthorized.' });
  }

  try {
    const token = authHeader.split(' ')[1];
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    req.user = decoded;
    next();
  } catch (error) {
    return res.status(401).json({ message: 'Invalid token.' });
  }
};
''')
add('review-service/src/controllers/reviewController.js', r'''
const axios = require('axios');
const Review = require('../models/Review');

exports.getReviewsByProduct = async (req, res) => {
  try {
    const reviews = await Review.find({ productId: req.params.productId }).sort({ createdAt: -1 });
    res.json(reviews);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.getReviewsByUser = async (req, res) => {
  try {
    const reviews = await Review.find({ userId: req.params.userId }).sort({ createdAt: -1 });
    res.json(reviews);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.createReview = async (req, res) => {
  try {
    const { productId, rating, title, comment } = req.body;

    await axios.get(`${process.env.PRODUCT_SERVICE_URL}/api/products/${productId}`);

    const review = await Review.create({
      userId: req.user.id,
      userName: req.user.name,
      productId,
      rating,
      title,
      comment
    });

    res.status(201).json({ message: 'Review created successfully.', review });
  } catch (error) {
    const message = error.response?.data?.message || error.message;
    res.status(500).json({ message });
  }
};

exports.updateReview = async (req, res) => {
  try {
    const review = await Review.findById(req.params.id);
    if (!review) {
      return res.status(404).json({ message: 'Review not found.' });
    }

    if (review.userId !== req.user.id) {
      return res.status(403).json({ message: 'You can update only your own review.' });
    }

    const { rating, title, comment } = req.body;
    review.rating = rating ?? review.rating;
    review.title = title ?? review.title;
    review.comment = comment ?? review.comment;

    await review.save();
    res.json({ message: 'Review updated successfully.', review });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

exports.deleteReview = async (req, res) => {
  try {
    const review = await Review.findById(req.params.id);
    if (!review) {
      return res.status(404).json({ message: 'Review not found.' });
    }

    if (review.userId !== req.user.id) {
      return res.status(403).json({ message: 'You can delete only your own review.' });
    }

    await review.deleteOne();
    res.json({ message: 'Review deleted successfully.' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
''')
add('review-service/src/routes/reviewRoutes.js', r'''
const express = require('express');
const router = express.Router();
const reviewController = require('../controllers/reviewController');
const authMiddleware = require('../middlewares/authMiddleware');

router.get('/product/:productId', reviewController.getReviewsByProduct);
router.get('/user/:userId', reviewController.getReviewsByUser);
router.post('/', authMiddleware, reviewController.createReview);
router.put('/:id', authMiddleware, reviewController.updateReview);
router.delete('/:id', authMiddleware, reviewController.deleteReview);

module.exports = router;
''')

# user-service
add('user-service/package.json', common_package.replace('SERVICE_NAME', 'user-service'))
add('user-service/.env.example', r'''
PORT=4004
SERVICE_NAME=user-service
MONGO_URI=mongodb://mongo:27017/authdb
JWT_SECRET=supersecretjwtkey
REVIEW_SERVICE_URL=http://review-service:4003
''')
add('user-service/Dockerfile', r'''
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4004
CMD ["npm", "start"]
''')
add('user-service/src/server.js', common_server.replace('ROUTES_PLACEHOLDER', "app.use('/api/users', require('./routes/userRoutes'));"))
add('user-service/src/config/db.js', common_db)
add('user-service/src/models/User.js', r'''
const mongoose = require('mongoose');

const userSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    gender: { type: String, default: 'Not specified' },
    address: { type: String, default: '' },
    contactNumber: { type: String, default: '' },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true }
  },
  { timestamps: true }
);

module.exports = mongoose.model('User', userSchema);
''')
add('user-service/src/middlewares/authMiddleware.js', r'''
const jwt = require('jsonwebtoken');

module.exports = function authMiddleware(req, res, next) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ message: 'Unauthorized.' });
  }

  try {
    const token = authHeader.split(' ')[1];
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    req.user = decoded;
    next();
  } catch (error) {
    return res.status(401).json({ message: 'Invalid token.' });
  }
};
''')
add('user-service/src/controllers/userController.js', r'''
const axios = require('axios');
const User = require('../models/User');

exports.getMyProfile = async (req, res) => {
  try {
    const user = await User.findById(req.user.id).select('-password');
    if (!user) {
      return res.status(404).json({ message: 'User not found.' });
    }

    const reviewsResponse = await axios.get(`${process.env.REVIEW_SERVICE_URL}/api/reviews/user/${req.user.id}`);

    res.json({
      user,
      reviews: reviewsResponse.data
    });
  } catch (error) {
    const message = error.response?.data?.message || error.message;
    res.status(500).json({ message });
  }
};

exports.getUserReviews = async (req, res) => {
  try {
    const reviewsResponse = await axios.get(`${process.env.REVIEW_SERVICE_URL}/api/reviews/user/${req.params.userId}`);
    res.json(reviewsResponse.data);
  } catch (error) {
    const message = error.response?.data?.message || error.message;
    res.status(500).json({ message });
  }
};
''')
add('user-service/src/routes/userRoutes.js', r'''
const express = require('express');
const router = express.Router();
const userController = require('../controllers/userController');
const authMiddleware = require('../middlewares/authMiddleware');

router.get('/me', authMiddleware, userController.getMyProfile);
router.get('/:userId/reviews', userController.getUserReviews);

module.exports = router;
''')

# gateway
add('api-gateway/package.json', r'''
{
  "name": "api-gateway",
  "version": "1.0.0",
  "main": "src/server.js",
  "scripts": {
    "start": "node src/server.js",
    "dev": "nodemon src/server.js"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "http-proxy-middleware": "^3.0.0",
    "morgan": "^1.10.0"
  },
  "devDependencies": {
    "nodemon": "^3.1.4"
  }
}
''')
add('api-gateway/.env.example', r'''
PORT=8080
AUTH_SERVICE_URL=http://auth-service:4001
PRODUCT_SERVICE_URL=http://product-service:4002
REVIEW_SERVICE_URL=http://review-service:4003
USER_SERVICE_URL=http://user-service:4004
''')
add('api-gateway/Dockerfile', r'''
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8080
CMD ["npm", "start"]
''')
add('api-gateway/src/server.js', r'''
const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const path = require('path');
const { createProxyMiddleware } = require('http-proxy-middleware');
require('dotenv').config();

const app = express();

app.use(cors());
app.use(morgan('dev'));
app.use(express.json());

app.use('/api/auth', createProxyMiddleware({ target: process.env.AUTH_SERVICE_URL, changeOrigin: true }));
app.use('/api/products', createProxyMiddleware({ target: process.env.PRODUCT_SERVICE_URL, changeOrigin: true }));
app.use('/api/reviews', createProxyMiddleware({ target: process.env.REVIEW_SERVICE_URL, changeOrigin: true }));
app.use('/api/users', createProxyMiddleware({ target: process.env.USER_SERVICE_URL, changeOrigin: true }));

app.use(express.static(path.join(__dirname, '../../frontend/public')));

app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, '../../frontend/public/index.html'));
});

const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(`API Gateway running on port ${PORT}`);
});
''')

# frontend
add('frontend/public/index.html', r'''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Customer Review App</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/styles.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container">
      <a class="navbar-brand fw-bold" href="#">ReviewHub</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navMenu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navMenu">
        <ul class="navbar-nav ms-auto align-items-lg-center gap-lg-2">
          <li class="nav-item"><a class="nav-link" href="#products">Products</a></li>
          <li class="nav-item"><a class="nav-link" href="#profile-section">Profile</a></li>
          <li class="nav-item"><button id="openLoginBtn" class="btn btn-outline-light btn-sm me-2">Login</button></li>
          <li class="nav-item"><button id="openRegisterBtn" class="btn btn-warning btn-sm me-2">Register</button></li>
          <li class="nav-item"><button id="logoutBtn" class="btn btn-danger btn-sm d-none">Logout</button></li>
        </ul>
      </div>
    </div>
  </nav>

  <header class="hero py-5">
    <div class="container text-center">
      <h1 class="display-5 fw-bold">Customer Review App</h1>
      <p class="lead">Browse products and services, then post and manage your reviews.</p>
      <button class="btn btn-light btn-lg" onclick="document.getElementById('products').scrollIntoView({behavior:'smooth'})">Explore Reviews</button>
    </div>
  </header>

  <main class="container my-5">
    <div id="alertBox"></div>

    <section id="products">
      <div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2">
        <h2 class="mb-0">Trending Products & Services</h2>
        <button id="seedBtn" class="btn btn-primary btn-sm">Seed Demo Products</button>
      </div>
      <div id="productList" class="row g-4"></div>
    </section>

    <section id="productDetailsSection" class="mt-5 d-none">
      <div id="productDetails"></div>
      <div class="card shadow-sm mt-4">
        <div class="card-body">
          <h4 class="mb-3">Reviews</h4>
          <div id="reviewList"></div>
        </div>
      </div>

      <div class="card shadow-sm mt-4">
        <div class="card-body">
          <h4 class="mb-3">Write a Review</h4>
          <form id="reviewForm">
            <div class="row g-3">
              <div class="col-md-2">
                <label class="form-label">Rating</label>
                <select id="rating" class="form-select" required>
                  <option value="">Select</option>
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                  <option>5</option>
                </select>
              </div>
              <div class="col-md-10">
                <label class="form-label">Review title</label>
                <input type="text" id="reviewTitle" class="form-control" required>
              </div>
              <div class="col-12">
                <label class="form-label">Comment</label>
                <textarea id="reviewComment" class="form-control" rows="4" required></textarea>
              </div>
            </div>
            <button class="btn btn-success mt-3" type="submit">Submit Review</button>
          </form>
        </div>
      </div>
    </section>

    <section id="profile-section" class="mt-5">
      <div class="card shadow-sm">
        <div class="card-body">
          <h2 class="mb-3">My Profile</h2>
          <div id="profileContent"><p class="text-muted mb-0">Log in to view your profile.</p></div>
        </div>
      </div>
    </section>
  </main>

  <div class="modal fade" id="authModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="authModalTitle">Login</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <form id="authForm"></form>
        </div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/app.js"></script>
</body>
</html>
''')
add('frontend/public/styles.css', r'''
body {
  background: #f8f9fa;
}

.hero {
  background: linear-gradient(135deg, #0d6efd, #6f42c1);
  color: white;
}

.product-card img {
  height: 220px;
  object-fit: cover;
}

.review-item {
  border-bottom: 1px solid #e9ecef;
  padding: 1rem 0;
}

.review-item:last-child {
  border-bottom: none;
}
''')
add('frontend/public/app.js', r'''
const api = {
  async get(url, token) {
    const res = await fetch(url, {
      headers: token ? { Authorization: `Bearer ${token}` } : {}
    });
    return res.json();
  },
  async post(url, body, token) {
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {})
      },
      body: JSON.stringify(body)
    });
    return res.json();
  },
  async put(url, body, token) {
    const res = await fetch(url, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {})
      },
      body: JSON.stringify(body)
    });
    return res.json();
  },
  async delete(url, token) {
    const res = await fetch(url, {
      method: 'DELETE',
      headers: token ? { Authorization: `Bearer ${token}` } : {}
    });
    return res.json();
  }
};

let selectedProductId = null;
let authMode = 'login';
const authModal = new bootstrap.Modal(document.getElementById('authModal'));

function getToken() {
  return localStorage.getItem('token');
}

function getUser() {
  const raw = localStorage.getItem('user');
  return raw ? JSON.parse(raw) : null;
}

function setSession(token, user) {
  localStorage.setItem('token', token);
  localStorage.setItem('user', JSON.stringify(user));
  updateAuthButtons();
}

function clearSession() {
  localStorage.removeItem('token');
  localStorage.removeItem('user');
  updateAuthButtons();
}

function showAlert(message, type = 'success') {
  document.getElementById('alertBox').innerHTML = `
    <div class="alert alert-${type} alert-dismissible fade show" role="alert">
      ${message}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
  `;
}

function updateAuthButtons() {
  const loggedIn = !!getToken();
  document.getElementById('logoutBtn').classList.toggle('d-none', !loggedIn);
  document.getElementById('openLoginBtn').classList.toggle('d-none', loggedIn);
  document.getElementById('openRegisterBtn').classList.toggle('d-none', loggedIn);
}

function renderAuthForm() {
  const form = document.getElementById('authForm');
  const title = document.getElementById('authModalTitle');
  title.textContent = authMode === 'login' ? 'Login' : 'Register';

  form.innerHTML = authMode === 'login' ? `
    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="email" id="authEmail" class="form-control" required>
    </div>
    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" id="authPassword" class="form-control" required>
    </div>
    <button class="btn btn-primary w-100" type="submit">Login</button>
  ` : `
    <div class="row g-3">
      <div class="col-12">
        <label class="form-label">Full name</label>
        <input type="text" id="authName" class="form-control" required>
      </div>
      <div class="col-md-6">
        <label class="form-label">Gender</label>
        <input type="text" id="authGender" class="form-control" placeholder="Male/Female/Other">
      </div>
      <div class="col-md-6">
        <label class="form-label">Contact number</label>
        <input type="text" id="authContact" class="form-control">
      </div>
      <div class="col-12">
        <label class="form-label">Address</label>
        <input type="text" id="authAddress" class="form-control">
      </div>
      <div class="col-12">
        <label class="form-label">Email</label>
        <input type="email" id="authEmail" class="form-control" required>
      </div>
      <div class="col-12">
        <label class="form-label">Password</label>
        <input type="password" id="authPassword" class="form-control" required>
      </div>
    </div>
    <button class="btn btn-success w-100 mt-3" type="submit">Create Account</button>
  `;
}

async function loadProducts() {
  const products = await api.get('/api/products');
  const list = document.getElementById('productList');

  if (!Array.isArray(products) || !products.length) {
    list.innerHTML = '<p class="text-muted">No products found yet. Click "Seed Demo Products".</p>';
    return;
  }

  list.innerHTML = products.map(product => `
    <div class="col-md-4">
      <div class="card h-100 shadow-sm product-card">
        <img src="${product.imageUrl}" class="card-img-top" alt="${product.name}">
        <div class="card-body d-flex flex-column">
          <span class="badge text-bg-primary align-self-start mb-2">${product.category}</span>
          <h5 class="card-title">${product.name}</h5>
          <p class="card-text">${product.description}</p>
          <p class="fw-bold mt-auto">$${product.price.toFixed(2)}</p>
          <button class="btn btn-outline-primary mt-2" onclick="showProductDetails('${product._id}')">View Details</button>
        </div>
      </div>
    </div>
  `).join('');
}

async function showProductDetails(productId) {
  selectedProductId = productId;
  const product = await api.get(`/api/products/${productId}`);
  const section = document.getElementById('productDetailsSection');
  const details = document.getElementById('productDetails');
  section.classList.remove('d-none');
  details.innerHTML = `
    <div class="card shadow-sm">
      <div class="row g-0">
        <div class="col-md-4"><img src="${product.imageUrl}" class="img-fluid rounded-start h-100" style="object-fit:cover;" alt="${product.name}"></div>
        <div class="col-md-8">
          <div class="card-body">
            <span class="badge text-bg-secondary mb-2">${product.category}</span>
            <h3>${product.name}</h3>
            <p>${product.description}</p>
            <p class="fw-bold">Price: $${product.price.toFixed(2)}</p>
          </div>
        </div>
      </div>
    </div>
  `;
  await loadReviews(productId);
  section.scrollIntoView({ behavior: 'smooth' });
}

async function loadReviews(productId) {
  const reviews = await api.get(`/api/reviews/product/${productId}`);
  const user = getUser();
  const list = document.getElementById('reviewList');

  if (!Array.isArray(reviews) || !reviews.length) {
    list.innerHTML = '<p class="text-muted">No reviews yet. Be the first to review this item.</p>';
    return;
  }

  list.innerHTML = reviews.map(review => `
    <div class="review-item">
      <div class="d-flex justify-content-between align-items-start flex-wrap gap-2">
        <div>
          <h5 class="mb-1">${review.title}</h5>
          <div class="small text-muted">By ${review.userName} • Rating: ${'★'.repeat(review.rating)}</div>
        </div>
        ${user && user.id === review.userId ? `
          <div class="d-flex gap-2">
            <button class="btn btn-sm btn-outline-secondary" onclick='editReview(${JSON.stringify(review).replace(/'/g, "&#39;")})'>Edit</button>
            <button class="btn btn-sm btn-outline-danger" onclick="deleteReview('${review._id}')">Delete</button>
          </div>
        ` : ''}
      </div>
      <p class="mb-0 mt-2">${review.comment}</p>
    </div>
  `).join('');
}

function editReview(review) {
  document.getElementById('rating').value = review.rating;
  document.getElementById('reviewTitle').value = review.title;
  document.getElementById('reviewComment').value = review.comment;
  document.getElementById('reviewForm').dataset.editId = review._id;
  showAlert('Editing review. Update the form and submit.', 'info');
}

async function deleteReview(reviewId) {
  const token = getToken();
  if (!token) {
    return showAlert('Please log in first.', 'warning');
  }
  const result = await api.delete(`/api/reviews/${reviewId}`, token);
  if (result.message) showAlert(result.message, 'success');
  await loadReviews(selectedProductId);
  await loadProfile();
}

async function loadProfile() {
  const token = getToken();
  const container = document.getElementById('profileContent');

  if (!token) {
    container.innerHTML = '<p class="text-muted mb-0">Log in to view your profile.</p>';
    return;
  }

  const data = await api.get('/api/users/me', token);
  if (data.message) {
    container.innerHTML = `<p class="text-danger mb-0">${data.message}</p>`;
    return;
  }

  const { user, reviews } = data;
  container.innerHTML = `
    <div class="row g-4">
      <div class="col-md-4">
        <div class="border rounded p-3 bg-light">
          <h5>${user.name}</h5>
          <p class="mb-1"><strong>Email:</strong> ${user.email}</p>
          <p class="mb-1"><strong>Gender:</strong> ${user.gender || 'N/A'}</p>
          <p class="mb-1"><strong>Contact:</strong> ${user.contactNumber || 'N/A'}</p>
          <p class="mb-0"><strong>Address:</strong> ${user.address || 'N/A'}</p>
        </div>
      </div>
      <div class="col-md-8">
        <h5 class="mb-3">My Reviews</h5>
        ${reviews.length ? reviews.map(review => `
          <div class="border rounded p-3 mb-3">
            <div class="d-flex justify-content-between">
              <strong>${review.title}</strong>
              <span>Rating: ${review.rating}/5</span>
            </div>
            <p class="mb-0 mt-2">${review.comment}</p>
          </div>
        `).join('') : '<p class="text-muted">You have not posted any reviews yet.</p>'}
      </div>
    </div>
  `;
}

document.getElementById('openLoginBtn').addEventListener('click', () => {
  authMode = 'login';
  renderAuthForm();
  authModal.show();
});

document.getElementById('openRegisterBtn').addEventListener('click', () => {
  authMode = 'register';
  renderAuthForm();
  authModal.show();
});

document.getElementById('logoutBtn').addEventListener('click', () => {
  clearSession();
  loadProfile();
  showAlert('Logged out successfully.', 'success');
});

document.getElementById('authForm').addEventListener('submit', async (e) => {
  e.preventDefault();

  let payload;
  let endpoint;

  if (authMode === 'login') {
    endpoint = '/api/auth/login';
    payload = {
      email: document.getElementById('authEmail').value,
      password: document.getElementById('authPassword').value
    };
  } else {
    endpoint = '/api/auth/register';
    payload = {
      name: document.getElementById('authName').value,
      gender: document.getElementById('authGender').value,
      address: document.getElementById('authAddress').value,
      contactNumber: document.getElementById('authContact').value,
      email: document.getElementById('authEmail').value,
      password: document.getElementById('authPassword').value
    };
  }

  const result = await api.post(endpoint, payload);
  if (result.token) {
    setSession(result.token, result.user);
    authModal.hide();
    showAlert(result.message, 'success');
    loadProfile();
  } else {
    showAlert(result.message || 'Request failed.', 'danger');
  }
});

document.getElementById('reviewForm').addEventListener('submit', async (e) => {
  e.preventDefault();
  const token = getToken();
  if (!token) {
    return showAlert('You must log in before posting a review.', 'warning');
  }
  if (!selectedProductId) {
    return showAlert('Please open a product first.', 'warning');
  }

  const payload = {
    productId: selectedProductId,
    rating: Number(document.getElementById('rating').value),
    title: document.getElementById('reviewTitle').value,
    comment: document.getElementById('reviewComment').value
  };

  const editId = e.target.dataset.editId;
  const result = editId
    ? await api.put(`/api/reviews/${editId}`, payload, token)
    : await api.post('/api/reviews', payload, token);

  showAlert(result.message || 'Action completed.', result.review ? 'success' : 'danger');
  e.target.reset();
  delete e.target.dataset.editId;
  await loadReviews(selectedProductId);
  await loadProfile();
});

document.getElementById('seedBtn').addEventListener('click', async () => {
  const result = await api.post('/api/products/seed', {});
  showAlert(result.message || 'Seed attempted.', 'info');
  await loadProducts();
});

renderAuthForm();
updateAuthButtons();
loadProducts();
loadProfile();
''')

add('docker-compose.yml', r'''
services:
  mongo:
    image: mongo:7
    container_name: review-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    container_name: product-service
    restart: unless-stopped
    env_file:
      - ./product-service/.env
    depends_on:
      - mongo

  review-service:
    build: ./review-service
    container_name: review-service
    restart: unless-stopped
    env_file:
      - ./review-service/.env
    depends_on:
      - mongo
      - product-service

  user-service:
    build: ./user-service
    container_name: user-service
    restart: unless-stopped
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo
      - review-service

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - product-service
      - review-service
      - user-service

volumes:
  mongo_data:
''')

# root convenience env copies
for svc in ['auth-service','product-service','review-service','user-service','api-gateway']:
    add(f'{svc}/.env', files[f'{svc}/.env.example'])

add('ARCHITECTURE.md', r'''
# Architecture Overview

## Microservices

### 1. API Gateway
Handles all browser requests and forwards API traffic to internal services.

### 2. Auth Service
Responsible for:
- user registration
- password hashing
- login
- JWT issuance
- token verification

### 3. Product Service
Responsible for:
- storing products/services
- listing products
- retrieving single product details
- seeding demo products

### 4. Review Service
Responsible for:
- storing reviews
- linking reviews to product IDs and user IDs
- enforcing ownership for update/delete

### 5. User Service
Responsible for:
- profile retrieval
- aggregation of user details and the user’s reviews

## MVC Inside Each Service
- **Model**: database schema and persistence logic
- **Controller**: business logic
- **Routes**: API endpoints
- **Middleware**: reusable logic such as authentication

## Data Separation
- `authdb`
- `productdb`
- `reviewdb`

This keeps domains isolated while still using one MongoDB container for development.
''')

for path, content in files.items():
    file_path = base / path
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(content, encoding='utf-8')

print(f'Created {len(files)} files')
